# Generated by Django 4.2.4 on 2023-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='AHC_ANC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='AHC_Full_ANC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='AHC_HI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='AHC_PNC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='AN_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='AN_W',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='C_UW',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='E_DropRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='Enrollment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='Equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='S_CoFu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='S_DrWa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='S_Elec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='S_Sani',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='W_BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='st_population',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='total_population',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
