# Generated by Django 4.2.4 on 2023-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0002_district_year_alter_district_ahc_anc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
