# Generated by Django 4.2.4 on 2024-01-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0003_district_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='slug',
        ),
    ]
