# Generated by Django 4.2.4 on 2024-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0004_remove_district_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
