# Generated by Django 4.2.4 on 2023-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_size', models.IntegerField(blank=True, null=True)),
                ('HH_score_C_L', models.BooleanField(blank=True, null=True)),
                ('HH_score_C_Arts', models.BooleanField(blank=True, null=True)),
                ('total_indicator', models.IntegerField(blank=True, null=True)),
                ('developed_indicator', models.IntegerField(blank=True, null=True)),
                ('Weightage', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('Is_Developed', models.BooleanField(blank=True, null=True)),
                ('E_H_members_of_developed_HHs', models.IntegerField(blank=True, null=True)),
                ('E_incidence', models.FloatField(blank=True, null=True)),
                ('E_intensity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_size', models.IntegerField(blank=True, null=True)),
                ('HH_score_E_LE', models.BooleanField(blank=True, null=True)),
                ('HH_score_E_DRO', models.BooleanField(blank=True, null=True)),
                ('total_indicator', models.IntegerField(blank=True, null=True)),
                ('developed_indicator', models.IntegerField(blank=True, null=True)),
                ('Weightage', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('Is_Developed', models.BooleanField(blank=True, null=True)),
                ('E_H_members_of_developed_HHs', models.IntegerField(blank=True, null=True)),
                ('E_incidence', models.FloatField(blank=True, null=True)),
                ('E_intensity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_size', models.IntegerField(blank=True, null=True)),
                ('HH_score_G_EV', models.BooleanField(blank=True, null=True)),
                ('HH_score_G_meeting', models.BooleanField(blank=True, null=True)),
                ('total_indicator', models.IntegerField(blank=True, null=True)),
                ('developed_indicator', models.IntegerField(blank=True, null=True)),
                ('Weightage', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('Is_Developed', models.BooleanField(blank=True, null=True)),
                ('E_H_members_of_developed_HHs', models.IntegerField(blank=True, null=True)),
                ('E_incidence', models.FloatField(blank=True, null=True)),
                ('E_intensity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_size', models.IntegerField(blank=True, null=True)),
                ('HH_score_H_CD', models.BooleanField(blank=True, null=True)),
                ('HH_score_H_IMM', models.BooleanField(blank=True, null=True)),
                ('HH_score_H_MC', models.BooleanField(blank=True, null=True)),
                ('HH_score_H_U5C', models.BooleanField(blank=True, null=True)),
                ('HH_score_H_FS', models.BooleanField(blank=True, null=True)),
                ('total_indicator', models.IntegerField(blank=True, null=True)),
                ('developed_indicator', models.IntegerField(blank=True, null=True)),
                ('Weightage', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('Is_Developed', models.BooleanField(blank=True, null=True)),
                ('H_incidence', models.FloatField(blank=True, null=True)),
                ('H_intensity', models.FloatField(blank=True, null=True)),
                ('H_H_members_of_developed_HHs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_Size', models.IntegerField(blank=True, null=True)),
                ('HH_Score_S_IC', models.BooleanField(blank=True, null=True)),
                ('HH_Score_S_OWN', models.BooleanField(blank=True, null=True)),
                ('HH_Score_S_SANI', models.BooleanField(blank=True, null=True)),
                ('HH_Score_S_Fuel', models.BooleanField(blank=True, null=True)),
                ('HH_Score_S_SoDrWa', models.BooleanField(blank=True, null=True)),
                ('HH_Score_S_ELECTR', models.BooleanField(blank=True, null=True)),
                ('HH_Score_S_ASS', models.BooleanField(blank=True, null=True)),
                ('total_indicator', models.IntegerField(blank=True, null=True)),
                ('developed_indicator', models.IntegerField(blank=True, null=True)),
                ('Weightage', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('Is_Developed', models.BooleanField(blank=True, null=True)),
                ('E_H_members_of_developed_HHs', models.IntegerField(blank=True, null=True)),
                ('E_incidence', models.FloatField(blank=True, null=True)),
                ('E_intensity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('H_DI', models.IntegerField()),
                ('E_DI', models.IntegerField()),
                ('SOL_DI', models.IntegerField()),
                ('C_DI', models.IntegerField()),
                ('G_DI', models.IntegerField()),
                ('incidence', models.FloatField(blank=True, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('tdi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
