# Generated by Django 4.2.4 on 2023-09-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='E_H_members_of_developed_HHs',
            new_name='C_H_members_of_developed_HHs',
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='E_incidence',
            new_name='C_incidence',
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='E_intensity',
            new_name='C_intensity',
        ),
        migrations.RenameField(
            model_name='governence',
            old_name='E_H_members_of_developed_HHs',
            new_name='G_H_members_of_developed_HHs',
        ),
        migrations.RenameField(
            model_name='governence',
            old_name='E_incidence',
            new_name='G_incidence',
        ),
        migrations.RenameField(
            model_name='governence',
            old_name='E_intensity',
            new_name='G_intensity',
        ),
        migrations.RenameField(
            model_name='sol',
            old_name='E_H_members_of_developed_HHs',
            new_name='S_H_members_of_developed_HHs',
        ),
        migrations.RenameField(
            model_name='sol',
            old_name='E_incidence',
            new_name='S_incidence',
        ),
        migrations.RenameField(
            model_name='sol',
            old_name='E_intensity',
            new_name='S_intensity',
        ),
    ]
