# Generated by Django 4.2.4 on 2023-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_e_h_members_of_developed_hhs_culture_c_h_members_of_developed_hhs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='HH_score_C_Arts',
            new_name='HH_Score_C_Arts',
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='HH_score_C_L',
            new_name='HH_Score_C_L',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='HH_score_E_DRO',
            new_name='HH_Score_E_DRO',
        ),
        migrations.RenameField(
            model_name='governence',
            old_name='HH_score_G_EV',
            new_name='HH_Score_G_EV',
        ),
        migrations.RenameField(
            model_name='governence',
            old_name='HH_score_G_meeting',
            new_name='HH_Score_G_meeting',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='HH_score_H_CD',
            new_name='HH_Score_H_CD',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='HH_score_H_FS',
            new_name='HH_Score_H_FS',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='HH_score_H_IMM',
            new_name='HH_Score_H_IMM',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='HH_score_H_MC',
            new_name='HH_Score_H_MC',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='HH_score_H_U5C',
            new_name='HH_Score_H_U5C',
        ),
        migrations.RemoveField(
            model_name='education',
            name='HH_score_E_LE',
        ),
        migrations.AddField(
            model_name='education',
            name='HH_Score_E_LE',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
