# Generated by Django 3.2.19 on 2023-09-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_hh_score_c_arts_culture_hh_score_c_arts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sol',
            old_name='HH_Size',
            new_name='HH_size',
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='C_DI',
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='E_DI',
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='G_DI',
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='H_DI',
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='SOL_DI',
        ),
    ]
