# Generated by Django 4.2.4 on 2023-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_governance_household_delete_governence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='HH_size',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='health',
            name='CD_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='CM_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='FS_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='IM_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='MC_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
