# Generated by Django 4.2.4 on 2023-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_hh_size_household_size_alter_health_cd_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='CD_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='CM_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='FS_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='IM_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='MC_score',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
