# Generated by Django 4.2.4 on 2023-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_household_cd_score_household_cm_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='CD_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='CM_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='FS_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='IM_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='MC_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
