# Generated by Django 4.2.4 on 2023-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_household_cd_score_alter_household_cm_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='HH',
        ),
        migrations.RemoveField(
            model_name='governance',
            name='HH',
        ),
        migrations.RemoveField(
            model_name='health',
            name='HH',
        ),
        migrations.RemoveField(
            model_name='sol',
            name='HH',
        ),
        migrations.RemoveField(
            model_name='household',
            name='no_of_H_indicators',
        ),
        migrations.AddField(
            model_name='household',
            name='ARTS_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='ASS_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='DRO_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='DRWA_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='ELECTR_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='FUEL_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='IC_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='LAN_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='LE_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='OW_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='SANI_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Governance',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='SOL',
        ),
    ]
