# Generated by Django 4.2.4 on 2023-09-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_education_hh_remove_governance_hh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='EV_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='MEET_score',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
