# Generated by Django 4.2.4 on 2023-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_household_ev_score_household_meet_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='tribe_name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
