# Generated by Django 4.2.4 on 2023-09-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_household_tribe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='tribe_name',
        ),
    ]
