# Generated by Django 4.2.4 on 2023-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_household_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='ide',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
