# Generated by Django 4.2.4 on 2023-09-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_household_tribeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribe',
            name='ide',
        ),
    ]
