# Generated by Django 4.2.5 on 2023-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_household_decimal_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='MC_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
