# Generated by Django 4.2.5 on 2023-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_household_mc_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='MC_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
