# Generated by Django 4.2.4 on 2023-10-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_household_mc_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='tribe_name',
        ),
    ]
