# Generated by Django 4.2.4 on 2023-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_tribe_image_date_alter_tribe_image_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribe_image',
            old_name='image',
            new_name='logo_image',
        ),
        migrations.RemoveField(
            model_name='tribe_image',
            name='date',
        ),
        migrations.AddField(
            model_name='tribe_image',
            name='main_image',
            field=models.ImageField(default='e', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribe_image',
            name='village_image',
            field=models.ImageField(default='e', upload_to='images'),
            preserve_default=False,
        ),
    ]
