# Generated by Django 4.2.4 on 2023-10-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_image_tribe_image_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='ARTS_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='ASS_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='CD_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='CM_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='DRO_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='DRWA_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='ELECTR_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='EV_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='FS_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='FUEL_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='IC_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='IM_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='LAN_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='LE_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='MC_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='MEET_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='OW_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='SANI_score',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
