# Generated by Django 4.2.4 on 2023-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_household_arts_score_alter_household_ass_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
