# Generated by Django 4.2.4 on 2023-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_tribe_image_main_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe_image',
            name='main_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='village_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
