# Generated by Django 4.2.4 on 2023-11-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_household_tribe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='tribe_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
