# Generated by Django 4.2.4 on 2023-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_household_tribe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe_image',
            name='logo_image',
            field=models.ImageField(upload_to='images/logo_images'),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='main_image',
            field=models.ImageField(upload_to='images/main_images'),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='map_image',
            field=models.ImageField(upload_to='images/map_images'),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='village_image',
            field=models.ImageField(upload_to='images/village_images'),
        ),
    ]
